package tomasn.lottery.mybatis.model;

public class ShareValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHARE_VALUE.SHARE_VALUE_ID
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    private Integer shareValueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHARE_VALUE.SHARE_DIVISION
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    private String shareDivision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHARE_VALUE.SHARE_WINNINGS
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    private Integer shareWinnings;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHARE_VALUE.SHARE_VALUE_ID
     *
     * @return the value of PUBLIC.SHARE_VALUE.SHARE_VALUE_ID
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public Integer getShareValueId() {
        return shareValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHARE_VALUE.SHARE_VALUE_ID
     *
     * @param shareValueId the value for PUBLIC.SHARE_VALUE.SHARE_VALUE_ID
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public void setShareValueId(Integer shareValueId) {
        this.shareValueId = shareValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHARE_VALUE.SHARE_DIVISION
     *
     * @return the value of PUBLIC.SHARE_VALUE.SHARE_DIVISION
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public String getShareDivision() {
        return shareDivision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHARE_VALUE.SHARE_DIVISION
     *
     * @param shareDivision the value for PUBLIC.SHARE_VALUE.SHARE_DIVISION
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public void setShareDivision(String shareDivision) {
        this.shareDivision = shareDivision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHARE_VALUE.SHARE_WINNINGS
     *
     * @return the value of PUBLIC.SHARE_VALUE.SHARE_WINNINGS
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public Integer getShareWinnings() {
        return shareWinnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHARE_VALUE.SHARE_WINNINGS
     *
     * @param shareWinnings the value for PUBLIC.SHARE_VALUE.SHARE_WINNINGS
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public void setShareWinnings(Integer shareWinnings) {
        this.shareWinnings = shareWinnings;
    }
}