package tomasn.lottery.mybatis.model;

import java.util.Date;

public class Ticket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TICKET.TICKET_ID
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    private Integer ticketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TICKET.NUMBERS
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    private String numbers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TICKET.PURCHASE_TIME
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    private Date purchaseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TICKET.TICKET_WINNINGS
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    private Integer ticketWinnings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TICKET.DRAW_ID
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    private Integer drawId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TICKET.TICKET_ID
     *
     * @return the value of PUBLIC.TICKET.TICKET_ID
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TICKET.TICKET_ID
     *
     * @param ticketId the value for PUBLIC.TICKET.TICKET_ID
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TICKET.NUMBERS
     *
     * @return the value of PUBLIC.TICKET.NUMBERS
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public String getNumbers() {
        return numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TICKET.NUMBERS
     *
     * @param numbers the value for PUBLIC.TICKET.NUMBERS
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public void setNumbers(String numbers) {
        this.numbers = numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TICKET.PURCHASE_TIME
     *
     * @return the value of PUBLIC.TICKET.PURCHASE_TIME
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public Date getPurchaseTime() {
        return purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TICKET.PURCHASE_TIME
     *
     * @param purchaseTime the value for PUBLIC.TICKET.PURCHASE_TIME
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public void setPurchaseTime(Date purchaseTime) {
        this.purchaseTime = purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TICKET.TICKET_WINNINGS
     *
     * @return the value of PUBLIC.TICKET.TICKET_WINNINGS
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public Integer getTicketWinnings() {
        return ticketWinnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TICKET.TICKET_WINNINGS
     *
     * @param ticketWinnings the value for PUBLIC.TICKET.TICKET_WINNINGS
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public void setTicketWinnings(Integer ticketWinnings) {
        this.ticketWinnings = ticketWinnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TICKET.DRAW_ID
     *
     * @return the value of PUBLIC.TICKET.DRAW_ID
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public Integer getDrawId() {
        return drawId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TICKET.DRAW_ID
     *
     * @param drawId the value for PUBLIC.TICKET.DRAW_ID
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    public void setDrawId(Integer drawId) {
        this.drawId = drawId;
    }
}