package tomasn.lottery.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import tomasn.lottery.mybatis.model.Draw;

@Mapper
public interface DrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRAW
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    int deleteByPrimaryKey(Integer drawId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRAW
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    int insert(Draw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRAW
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    Draw selectByPrimaryKey(Integer drawId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRAW
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    List<Draw> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRAW
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    int updateByPrimaryKey(Draw record);
}