package tomasn.lottery.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import tomasn.lottery.mybatis.model.ShareValue;

@Mapper
public interface ShareValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHARE_VALUE
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    int deleteByPrimaryKey(Integer shareValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHARE_VALUE
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    int insert(ShareValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHARE_VALUE
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    ShareValue selectByPrimaryKey(Integer shareValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHARE_VALUE
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    List<ShareValue> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHARE_VALUE
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    int updateByPrimaryKey(ShareValue record);
}