package tomasn.lottery.mybatis.dao;

import java.util.List;

import jdk.jfr.SettingDefinition;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.mybatis.cdi.Mapper;
import tomasn.lottery.mybatis.model.Ticket;

@Mapper
public interface TicketMapper {
    @Select("select * from ticket where draw_id = #{drawId}")
    List<Ticket> selectByDrawId(@Param("drawId") Integer drawId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TICKET
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    int deleteByPrimaryKey(Integer ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TICKET
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    int insert(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TICKET
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    Ticket selectByPrimaryKey(Integer ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TICKET
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    List<Ticket> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TICKET
     *
     * @mbg.generated Wed Apr 14 14:43:00 EEST 2021
     */
    int updateByPrimaryKey(Ticket record);
}